Use Object Store (draft)
kaskada-ai/kaskada pull request #231
Opened 2023-04-17 16:00 UTC by kevinjnguyen

2023-04-19 20:44 UTC, epinzur commented on wren/service/table.go
> -	}
I don't think this should be removed.

2023-04-19 20:50 UTC, epinzur commented on wren/compute/prepare.go
> +			OutputPathPrefix: prepareOutputURI,
if sparrow now supports all the standard file URIs correctly (`file:///, s3://, gs://, https://`) then there are probably several other places where `ConvertURIForCompute` and its partner `ConvertURIForManager` should be removed.

Ideally both functions should be removed in their entirety.

2023-04-21 12:02 UTC, epinzur requested changes
please re-add the code path in wren that copies files to the owned storage location, so that we don't change current functionality of the system.

2023-04-26 15:28 UTC, jordanrfrazier approved these changes

2023-04-27 07:59 UTC, epinzur approved these changes

2023-05-01 20:17 UTC, merged